# fly.toml app configuration file generated for universe-ampoi on 2024-03-13T13:25:51+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'universe-ampoi'
primary_region = 'nrt'

[build]
  dockerfile = 'dockerfile'

[http_service]
  internal_port = 6333
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
